### ISSUE TITLE
Sample in readme broken

### ISSUE THREAD

**Issue by olivergierke** [jpenren/thymeleaf-spring-data-dialect#3]
The sample in the readme shows:

```html
<div class="row">
    <div class="col-sm-6">
        <div sd:pagination-summary>info</div>
    </div>
   …
</div>
´´´

The incorrect usage of an HTML attribute results in:

```
org.xml.sax.SAXParseException: Mit Elementtyp "div" verknüpfter Attributname "sd:pagination-summary" muss vom Zeichen " = " gefolgt werden.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[na:1.8.0]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441) ~[na:1.8.0]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368) ~[na:1.8.0]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436) ~[na:1.8.0]
…
```

Which basically translates to "The attribute 'sd:pagination-summary' has to be followed by a ' = '".

**Comment by jpenren** [comment]
Thymeleaf 2 requires xml well formed, the right syntax is: sd:pagination-summary=""

Readme fixed, thanks @olivergierke
